print('-----------------------------------------------------------------------')
print('\t\tstudent Information')
print('-----------------------------------------------------------------------')
print('\t\t\tName    : sarathi')
print('\t\t\tAge     : 20')
print('\t\t\tMobile  : 7339259341')
print('\t\t\tEmail Id: gvijayasarathi286@gmail.com')
print('\t\t\tAddress : No.62 Bharathi thasan st R.K Nagar, Ariyankuppam,puducherry')
print('-----------------------------------------------------------------------')
